version: '3'

services:
  influxdb:
    image: influxdb:2.7.3
    volumes:
      - ./volumes/influxdb:/var/lib/influxdb
      - ./influx/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    networks:
      - adapter_db_network

  app:
    image: app
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - INFLUXDB_DB=iot_data
      - DEBUG_DATA_FLOW=true
    depends_on:
      - influxdb
    networks:
      - adapter_db_network
    restart: always
    ports:
      - 8443:443
networks:
  adapter_db_network: {} # adapter + influx