version: '3'

services:
  influxdb2:
    image: influxdb:2.6-alpine
    volumes:
      - ./volumes/influxdb:/var/lib/influxdb2:rw
      # - ./influx/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    networks:
      - adapter_db_network
    env_file:
      - ./influx/influxdb.env
    ports:
      - "8086:8086"

  app:
    image: app
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - INFLUXDB_DB=iot_data
      - DEBUG_DATA_FLOW=true
    depends_on:
      - influxdb2
    networks:
      - adapter_db_network
    restart: always
    ports:
      - 8443:8443

  # frontend:
  #   image: frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 80:3000

networks:
  adapter_db_network: {} # adapter + influx